from typing import Any, Dict

from config import config
from utilities.logger import logger
from utilities.parsers import (
    clean_text_for_tfsec, clean_text_for_trivy,
    extract_blocks_working_directory, get_paths_from_errors_checkov,
    get_paths_from_errors_tflint, get_paths_from_errors_tfsec,
    get_paths_from_errors_trivy,
    replace_relative_paths_to_absolute_in_errors_checkov,
    replace_relative_paths_to_absolute_in_errors_terraform,
    replace_relative_paths_to_absolute_in_errors_tfsec,
    replace_relative_paths_to_absolute_in_errors_trivy)
from utilities.vcs import get_all_tf_files_from_paths_list


def process_utilities_error_blocks(
        working_directory: str,
        errors: str,
        tool_name_lower: str,
) -> tuple[str, list[str]]:
    """
    Processes error messages for various tools, adjusts paths, and extracts files to analyze based on
    the specific tool being utilized. Operates conditionally to handle tool-specific variations when
    managing error data.

    Args:
        working_directory: The absolute path to the directory where the tool's analysis operates.
        errors: The error messages generated by the tool that require processing.
        tool_name_lower: The lowercase name of the tool that produced the errors. Must be one of
            the following: 'tflint', 'terraform', 'checkov', 'tfsec', or 'trivy'.

    Returns:
        A tuple where:
            - The first element is the processed error messages as a string.
            - The second element is a list of absolute file paths derived from the error messages
              or the working directory.
    """
    if tool_name_lower == 'tflint':
        paths_to_files: list[str] = get_paths_from_errors_tflint(errors)
        if not paths_to_files:
            paths_to_files = [working_directory]
        return errors, paths_to_files

    if tool_name_lower == 'terraform':
        errors = replace_relative_paths_to_absolute_in_errors_terraform(working_directory, errors)
        return errors, [working_directory]

    if tool_name_lower == 'checkov':
        errors = replace_relative_paths_to_absolute_in_errors_checkov(working_directory, errors)
        return errors, get_paths_from_errors_checkov(errors)

    if tool_name_lower == 'tfsec':
        errors = clean_text_for_tfsec(errors)
        errors = replace_relative_paths_to_absolute_in_errors_tfsec(working_directory, errors)
        return errors, get_paths_from_errors_tfsec(errors)

    if tool_name_lower == 'trivy':
        errors = clean_text_for_trivy(errors)
        errors = replace_relative_paths_to_absolute_in_errors_trivy(working_directory, errors)
        paths_to_files: list[str] = get_paths_from_errors_trivy(errors)
        if not paths_to_files:
            paths_to_files = [working_directory]
        return errors, paths_to_files

    return '', []


def make_prompt_block_with_errors_and_files(event: Dict[str, Any],
                                            errors_data: str) -> str:
    """
    Generates a formatted prompt block with errors, guides, and file contents, based on
    the provided event and errors data. The function processes errors, extracts relevant
    information, and associates them with corresponding file contents.

    Args:
        event (Dict[str, Any]): A dictionary containing event metadata and related data.
        errors_data (str): A string representing the errors data to be processed.

    Returns:
        str: A formatted multi-line string containing processed errors, guide information,
        and file contents.
    """
    prompt_block = """"""
    guide_block = """"""
    tool_name_lower = event.get('metadata', {}).get('tool_name', '').lower()

    if config.rag_enabled:
        pass

        # guide_block = extract_all_guides_secutils(errors_data, tool_name)

    extracted_blocks: list[tuple[str, str]] = extract_blocks_working_directory(errors_data)

    for working_directory, errors in extracted_blocks:
        logger.debug(f"Parsed working directory: {working_directory}.")
        logger.debug(f"Extracted error block >\n{errors}")
        files_block = """"""
        errors, paths_to_files = process_utilities_error_blocks(working_directory, errors, tool_name_lower)

        files_and_content = get_all_tf_files_from_paths_list(event, paths_to_files)

        for file_path, file_content in files_and_content:
            files_block += f"File content on: {file_path}\n\n```hcl\n{file_content}\n```\n"

        prompt_block += errors + "\n\n" + guide_block + "\n\n" + files_block + "\n"

    logger.debug(f"Prepared prompt >\n{prompt_block}")

    return prompt_block


def prepare_user_prompt_message(event: Dict[str, Any]) -> Dict[str, str]:
    """
    Prepares a user prompt message based on the provided event data. This includes processing
    errors and generating the formatted prompt content to be used in subsequent operations.

    Args:
        event (Dict[str, Any]): The event data containing metadata, errors, and other necessary
            context required to construct the user prompt.

    Returns:
        Dict[str, str]: A dictionary containing the role and the generated prompt content.
    """
    errors_text: str = event.get('metadata', {}).get('log_file_content', '')
    prompt: str = make_prompt_block_with_errors_and_files(event, errors_text).strip()
    event.get("metadata", {}).update({"prompt": prompt})

    return {'role': 'user', 'content': prompt}
