name: Tmp Hyphen Test

on:
  push:
    branches:
      - EPMCACMAWS-464-Kotova-scanner-reusable-workflow

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      my-test-var: "hello"
    steps:
      - name: dot notation with hyphen
        if: env.my-test-var == 'hello'
        run: echo "DOT NOTATION WORKED"

      - name: bracket notation
        if: env['my-test-var'] == 'hello'
        run: echo "BRACKET NOTATION WORKED"

      - name: always print for comparison
        if: always()
        run: echo "reached end of job"
