name: Tmp Hyphen Test

on:
  push:
    branches:
      - EPMCACMAWS-464-Kotova-scanner-reusable-workflow

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      my-test-var: "hello-world"
    steps:
      - name: dot notation in string interpolation
        run: echo "INTERP DOT = ${{ env.my-test-var }}"

      - name: bracket notation in string interpolation
        run: echo "INTERP BRACKET = ${{ env['my-test-var'] }}"

      - name: dot notation used as a value not just condition
        env:
          RESULT: ${{ env.my-test-var }}
        run: echo "AS ENV VALUE = $RESULT"
